{
 "title": "Application - Request Log",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "workload",
    "query": {}
   },
   {
    "name": "vm",
    "query": {}
   },
   {
    "name": "protocol",
    "query": {}
   },
   { "name": "request_type", "query": "*" },
   { "name": "request_resource", "query": "*" },
   {
    "name": "status",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Help doc",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "[English doc](https://deepflow.yunshan.net/metaflow-docs/auto-metrics/request-log/?from_metaflow_grafana) | [中文文档](https://deepflow.yunshan.net/metaflow-docs/zh/auto-metrics/request-log/?from_metaflow_grafana) \n"
   }
  },
  {
   "title": "Summary count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"baf6fa96-e59c-f572-7486-ce275a28f4e3\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_type\",\"label\":\"$request_type\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0e5ed5ea-1b2b-7beb-ec92-64d44af65de7\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_resource\",\"label\":\"$request_resource\"}],\"as\":\"\",\"params\":[],\"uuid\":\"baa9e9d0-babd-8e27-5255-f4967774ca18\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"41004d35-a477-e1d7-40d1-1537189f3164\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"f2ebec22-6c8d-f681-3842-d94c34873dba\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"8dd5d666-bb06-8e31-88f5-1ddd8898d2f0\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"b76452b2-fc34-de28-a1f7-819995835d40\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$status\",\"value\":\"status\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"7145be3f-04f1-2e0e-da28-63950b186cb3\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$protocol\",\"value\":\"protocol\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"0043a05c-fbe1-0888-0ab5-8616c34c8c5b\",\"subFuncs\":[],\"whereOnly\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fb7a5836-a9aa-8d6c-24c5-7ebc741939e0\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ba1f0f84-a5ce-18d7-ea9d-fdf2a2bcbc28\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9a18fb31-d9d6-2269-6e92-971a0970cde1\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"客户端异常-Sum(日志总量)\",\"params\":[],\"uuid\":\"baf6fa96-e59c-f572-7486-ce275a28f4e3\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"客户端异常\",\"value\":4}],\"as\":\"\",\"params\":[],\"uuid\":\"7bf0189d-5a77-39f1-2cc1-155fa4ded60e\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_type\",\"label\":\"$request_type\"}],\"as\":\"\",\"params\":[],\"uuid\":\"0cbf1257-60bc-b97e-a34f-ba9279a6eb88\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_resource\",\"label\":\"$request_resource\"}],\"as\":\"\",\"params\":[],\"uuid\":\"9a84caea-973f-b1e3-7f89-cf8979108ad2\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"33186dbe-0e65-13f0-6eae-d7b66833f87b\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"aaa10cee-3317-5a62-6a73-438c1e07ccdb\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"0094850f-488f-2a42-2514-f8c0bf3cafcb\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"316cacf2-0423-405b-198c-a6c71ea665d6\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$status\",\"value\":\"status\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"4d166911-2326-4061-453e-f70e65e6865c\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$protocol\",\"value\":\"protocol\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"48ea195d-b115-7619-6ee7-4164982a5efe\",\"subFuncs\":[],\"whereOnly\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fb7a5836-a9aa-8d6c-24c5-7ebc741939e0\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b5c331ad-afde-bd6d-b79e-4315f4fc6cf7\",\"subFuncs\":[]}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9a18fb31-d9d6-2269-6e92-971a0970cde1\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    },
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"log_count\",\"func\":\"Sum\",\"op\":\"\",\"val\":\"\",\"as\":\"服务端异常-Sum(日志总量)\",\"params\":[],\"uuid\":\"baf6fa96-e59c-f572-7486-ce275a28f4e3\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"服务端异常\",\"value\":3}],\"as\":\"\",\"params\":[],\"uuid\":\"7bf0189d-5a77-39f1-2cc1-155fa4ded60e\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"78a9d494-a0ef-3602-33ca-2e677efa147c\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"1001ab2c-2fcc-23d5-2ca0-4a02ec7ecb97\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"3f6f8183-bc2b-d9ab-e9fc-1246c4c09b79\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"7185a11c-4887-9e84-4747-da99c902933d\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$protocol\",\"value\":\"protocol\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"91bb6c10-3b2a-e136-2af5-6b8b832416dc\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$request_type\",\"value\":\"request_type\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"633df6e6-d158-53ed-b5e9-db5232885644\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$request_resource\",\"value\":\"request_resource\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"6960f850-2939-3004-2e3a-f636e2f44d1c\",\"subFuncs\":[],\"whereOnly\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fb7a5836-a9aa-8d6c-24c5-7ebc741939e0\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b5c331ad-afde-bd6d-b79e-4315f4fc6cf7\",\"subFuncs\":[]}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9a18fb31-d9d6-2269-6e92-971a0970cde1\",\"sort\":\"asc\"}],\"interval\":\"60\",\"limit\":\"\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "Latency histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"a5065067-fd9d-a262-ec4a-195a7460c837\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_type\",\"label\":\"$request_type\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4a51be5a-de57-1470-1fca-e6e7ac937b41\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_resource\",\"label\":\"$request_resource\"}],\"as\":\"\",\"params\":[],\"uuid\":\"4fe7f293-e9b3-55ac-2cec-8a047db42a3f\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"7a92dc1a-9e49-2245-13d7-7da19e002571\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"ef0ecb40-8dda-d04a-1c15-69be4273558c\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"1cc4e032-f49b-10b6-6b1f-ae6f3acbbbf7\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"5d529ff3-5350-5aeb-dff2-f0c351bf0caf\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$status\",\"value\":\"status\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"2b4a2635-6748-ae47-9658-ce4214f40e0d\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$protocol\",\"value\":\"protocol\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"b3691c3c-db10-d9e4-cfab-2f0cb6ff9311\",\"subFuncs\":[],\"whereOnly\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fb7a5836-a9aa-8d6c-24c5-7ebc741939e0\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ba1f0f84-a5ce-18d7-ea9d-fdf2a2bcbc28\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9a18fb31-d9d6-2269-6e92-971a0970cde1\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  },
  {
   "title": "Request log",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "{\"appType\":\"trafficQuery\",\"db\":\"flow_log\",\"sources\":\"\",\"from\":\"l7_flow_log\",\"select\":[{\"type\":\"tag\",\"key\":\"start_time\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"54447727-0443-817d-ba0b-1f6f87126e7e\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"resource_gl0_0\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"6c0790e1-e1f7-0726-50fa-638a20357f45\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"resource_gl0_1\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b5e4c33c-7627-a95f-fba0-007c9054fd7b\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ccc64c9e-5b42-b77d-e836-8da6926e3b08\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"0db10a0e-94f7-1585-0132-9a93ed9aacad\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_domain\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7d4ea1ee-122d-cb46-dfae-a59c3074fa3f\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"7627d817-282d-b982-b507-ac9df21d48dc\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"b12c4bd4-09fb-8cf0-4475-6c2d9cc37a9c\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"response_code\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9ca6471b-055e-9155-ca34-52b9b824649b\",\"subFuncs\":[]},{\"type\":\"metric\",\"key\":\"response_duration\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"d2389025-7e9e-5200-e45f-255117987b86\",\"subFuncs\":[]}],\"where\":[{\"type\":\"tag\",\"key\":\"request_type\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_type\",\"label\":\"$request_type\"}],\"as\":\"\",\"params\":[],\"uuid\":\"ce2f7fb2-77fd-cdb4-6597-c6bc13486c9c\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"request_resource\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"value\":\"$request_resource\",\"label\":\"$request_resource\"}],\"as\":\"\",\"params\":[],\"uuid\":\"e81dc89a-ea8e-7908-467a-d1400e84d300\",\"subFuncs\":[]},{\"type\":\"tag\",\"key\":\"pod_cluster\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$cluster\",\"value\":\"cluster\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"12fa6c20-0cd9-ef8c-5089-59ef0b005151\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_ns\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$namespace\",\"value\":\"namespace\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"99b642c7-b640-7dea-482f-9094e3737364\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"pod_group\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$workload\",\"value\":\"workload\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"8766e075-187a-265b-ce99-21a90d8bb484\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"chost\",\"func\":\"\",\"op\":\"LIKE\",\"val\":[{\"label\":\"$vm\",\"value\":\"vm\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"7e95f22c-0f14-1713-c7ac-28161fccfe47\",\"subFuncs\":[],\"whereOnly\":true},{\"type\":\"tag\",\"key\":\"response_status\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$status\",\"value\":\"status\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"facc1670-bc8c-24ca-0be4-c06627ec3892\",\"subFuncs\":[],\"whereOnly\":false},{\"type\":\"tag\",\"key\":\"l7_protocol\",\"func\":\"\",\"op\":\"IN\",\"val\":[{\"label\":\"$protocol\",\"value\":\"protocol\",\"isVariable\":true}],\"as\":\"\",\"params\":[],\"uuid\":\"392bf2ca-0c84-cb38-642a-c96530f58314\",\"subFuncs\":[],\"whereOnly\":false}],\"having\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"fb7a5836-a9aa-8d6c-24c5-7ebc741939e0\"}],\"groupBy\":[{\"type\":\"tag\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"ba1f0f84-a5ce-18d7-ea9d-fdf2a2bcbc28\"}],\"orderBy\":[{\"type\":\"metric\",\"key\":\"\",\"func\":\"\",\"op\":\"\",\"val\":\"\",\"as\":\"\",\"params\":[],\"uuid\":\"9a18fb31-d9d6-2269-6e92-971a0970cde1\",\"sort\":\"asc\"}],\"interval\":\"\",\"limit\":\"1000\",\"offset\":\"\",\"formatAs\":\"timeSeries\",\"alias\":\"\"}"
    }
   ]
  }
 ]
}