global:
  image:
    ## Dockerhub Image repository address: deepflowys/deepflow-server
    ## AliyunYun Image repository address: registry.cn-beijing.aliyuncs.com/deepflowys/deepflow-server
    repository: registry.cn-beijing.aliyuncs.com/deepflowys
  replicas: 2

mysql:
  # securityContext:
  #   privileged: true
  storageConfig:
    hostPathChownContainerEnabled: true
    ## persistentVolumeClaim/hostPath
    ## If you use hostPath, you must configure nodeAffinityLabelSelector, otherwise your data will be lost when Pod drifts
    ## 如果使用hostPath存储mysql数据，则必须配置nodeAffinityLabelSelector，避免pod漂移导致数据丢失
    type: hostPath
    hostPath: /opt/deepflow-455
  nodeAffinityLabelSelector: 
    ## If you use hostPath, you must configure nodeAffinityLabelSelector, otherwise your data will be lost when Pod drifts
    ## 如果使用hostPath存储mysql数据，则必须配置nodeAffinityLabelSelector，避免pod漂移导致数据丢失
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: cn-chengdu.172.16.0.196

clickhouse:
  storageConfig:
    ## persistentVolumeClaim/hostPath
    ## If you use hostPath, you must configure nodeAffinityLabelSelector, otherwise your data will be lost when Pod drifts
    ## 如果使用hostPath存储mysql数据，则必须配置nodeAffinityLabelSelector，避免pod漂移导致数据丢失
    type: hostPath
  nodeAffinityLabelSelector: 
    ## If you use hostPath, you must configure nodeAffinityLabelSelector, otherwise your data will be lost when Pod drifts
    ## 如果使用hostPath存储mysql数据，则必须配置nodeAffinityLabelSelector，避免pod漂移导致数据丢失
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: cn-chengdu.172.16.0.196 
deepflow-agent:
  deepflowAgentConfig: 
    deepflow-agent.yaml: |
      controller-ips:
      - deepflow-server
      kubernetes-cluster-id: d-01NKgARSKK 

#
#