# Default values for metaflow-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  podAntiAffinityLabelSelector: []
  podAntiAffinityTermLabelSelector: []
  podAffinityLabelSelector: []
  podAffinityTermLabelSelector: []
  nodeAffinityLabelSelector: []
  nodeAffinityTermLabelSelector: []


image:
  repository: registry.cn-beijing.aliyuncs.com/metaflowys/metaflow-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
hostNetwork: "true"
securityContext: 
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  
nodeIPInjection: false

service:
  ## Configuration for Clickhouse service
  ##
  annotations: {}
  labels: {}
  clusterIP: ""

  ## Port for Clickhouse Service to listen on
  ##

  ports:
  - name: otel
    port: 4317
    targetPort: 4317
    nodePort: 
    protocol: TCP

  ## Additional ports to open for server service
  additionalPorts: []

  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
  ## must be Local
  externalTrafficPolicy: Local

  ## Service type
  ##
  type: ClusterIP

metaflowServerNodeIps:
- metaflow-server
kubernetesClusterId: 
agentGroupId: 

metaflowAgentConfig: 
  metaflow-agent.yaml: |
    controller-ips:
    {{ toYaml $.Values.metaflowServerNodeIps }}
    {{ if .Values.kubernetesClusterId }}vtap-group-id-request: {{ .Values.kubernetesClusterId }}{{ end }}
    {{ if .Values.agentGroupId }}kubernetes-cluster-id: {{ .Values.agentGroupId }}{{ end }}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

podAntiAffinityLabelSelector: []
podAntiAffinityTermLabelSelector: []
podAffinityLabelSelector: []
podAffinityTermLabelSelector: []
nodeAffinityLabelSelector: []
nodeAffinityTermLabelSelector: []

