apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "metaflow-agent.fullname" . }}
  labels:
    {{- include "metaflow-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metaflow-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        container.apparmor.security.beta.kubernetes.io/metaflow-agent: unconfined
      {{- end }}
      labels:
        {{- include "metaflow-agent.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ tpl .Values.hostNetwork . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metaflow-agent.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ tpl .Values.image.tag .}}"
          imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
          ports:
            - name: otel
              containerPort: 4317
              protocol: TCP
          # livenessProbe:
          #   tcpSocket:
          #     port: otel
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   tcpSocket:
          #     port: otel
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
              readOnly: false ## load ebpf bytecode into kernel
            - name: metaflow-agent-conf
              mountPath: /etc/metaflow-agent
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: metaflow-agent-conf
          configMap:
            name: {{ include "metaflow-agent.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      {{- if or .Values.global.tolerations .Values.tolerations }}
      tolerations:
      {{- if .Values.global.tolerations }}
      {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- end }}