{{- if and (eq .Values.storageConfig.type "persistentVolumeClaim") (not .Values.storageConfig.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mysql.fullname" . }}-data-pvc
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.storageConfig.persistence.annotations | nindent 4 }}
spec:
  {{- if (ne "-" .Values.storageConfig.persistence.storageClass) }}
  storageClassName: {{ tpl .Values.storageConfig.persistence.storageClass . | quote }}
  storageClassName: ""
  {{- end }}
  accessModes:
  - {{ .Values.storageConfig.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storageConfig.persistence.size | quote }}
{{- end -}}