name: Release Charts

on:
  push:
    branches:
      - v6.1
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true 
        type: string

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: shell
        run: |
          echo ${{ github.ref_name }}
          echo "to 6.1 latest"

  sync_image:
    name: sync image
    runs-on: ubuntu-latest
    needs: 
    - release
    steps: 
      - name: shell
        run: |
          echo ${{ github.ref_name }}
          echo "sync stable image"
          echo "sync v6.1 image"

  release_stable_chart:
    name: release stable chart
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v') && !startsWith(github.ref, 'refs/tags/v6.1.8.')" #### to stable
    steps:
      - name: shell
        run: |
          echo ${{ github.ref_name }}
          echo "to stable"


  release_6_1_lts_chart:
    name: release 6.1 lts chart
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v6.1.8') || startsWith(github.ref, 'refs/tags/v6.1.8.')" #### to lts
    steps:
      - name: shell
        run: |
          echo ${{ github.ref_name }}
          echo "to 6.1 lts"
